ruby '2.2.0'
source('http://ruby.taobao.org')

gem 'rails', '4.2.0'
gem 'sqlite3'
gem 'grape'

# Auth
gem 'bcrypt'

# Front-end
gem 'slim-rails'
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass', '~> 3.3.3'
gem 'uglifier', '>= 1.3.0'

group :development do
  # Pry
  gem 'pry-rails'
  gem 'pry-byebug'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

